### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1318: ordinal not in range(128)

### ISSUE THREAD

**Issue by Luis-Palacios** [mishbahr/djangocms-gmaps#2]
Hello, i am able to install without any problem with pip install in my dev machine (OS:Windows), but when trying to do a pip install djangocms-gmaps on the production server (BlueHost Shared Server)
i am getting the following error:

> Collecting djangocms-gmaps
>   Using cached djangocms-gmaps-0.1.1.tar.gz
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "/var/tmp/pip-build-efkh4eg1/djangocms-gmaps/setup.py", line 23, in <module>
>         readme = open('README.rst').read()
>       File "/home2/hamilub0/django_projects/hamiltonresourcescms/env/lib/python3.4/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1318: ordinal not in range(128)
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):

```
  File "<string>", line 20, in <module>

  File "/var/tmp/pip-build-efkh4eg1/djangocms-gmaps/setup.py", line 23, in <module>

    readme = open('README.rst').read()

  File "/home2/hamilub0/django_projects/hamiltonresourcescms/env/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1318: ordinal not in range(128)

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/tmp/pip-build-efkh4eg1/djangocms-gmaps
```

They both have python 3.4, django 1.7.5 and django-cms 3.0.12

**Comment by mishbahr** [comment]
Pushed fix to PyPi  :-)

**Comment by Luis-Palacios** [comment]
It works nows thanks a lot
