### ISSUE TITLE
Feature Request - Customisable template

### ISSUE THREAD

**Issue by leesolway** [mishbahr/djangocms-gmaps#4]
Add support for multiple templates, powered by settings.. 

For example:

```
DJANGOCMS_GMAPS_TEMPLATES = (
    ('default', 'Default'),
    ('wide', 'Wide'),
)
```

Also the ability to set the default template would be useful.

**Comment by mishbahr** [comment]
I've added this to my list of future enhancements. I'll close this.. not really an issue.
