### ISSUE TITLE
DJANGOCMS_GMAPS_TEXT_ENABLED doesn't appear to work

### ISSUE THREAD

**Issue by db654** [mishbahr/djangocms-gmaps#6]
From testing, then checking the cms_plugins.py file to see whether this configuration option actually sets the text_enabled param, it doesn't seem to be functional in version 0.1.4.0.

**Comment by mishbahr** [comment]
Thanks for reporting the issue. 

Looks like I forgot to add `text_enabled` setting. 
I'll  push a fix asap. 

Regards 

Mishbah

**Comment by db654** [comment]
Thanks for the quick reply! Great flexible plugin.
