### ISSUE TITLE
It seems something has changed at Google

### ISSUE THREAD

**Issue by mkoistinen** [mishbahr/djangocms-gmaps#7]
And now we require a (free) API key? Do you plan to support this?

**Comment by mishbahr** [comment]
Yes. I'll look into this.

**Comment by mishbahr** [comment]
Hey @mkoistinen, can you please review my latest changes.. I don't have CMS project to test with. Thanks.

**Comment by mkoistinen** [comment]
Hi Mishbahr,

It works brilliantly on localhost, but when I deploy to a real internet address, I get:

![image](https://cloud.githubusercontent.com/assets/615759/17120806/cc45bbf6-529c-11e6-9b38-7081df297401.png)

I did set the new setting: `DJANGOCMS_GMAPS_API_KEY = '«my Google API key»'`. Unclear what the deal is.

**Comment by mishbahr** [comment]
Why would it work locally? but not on a live site?

Are you using custom template?

**Comment by mishbahr** [comment]
Official docs is not that useful!

https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

**Comment by mkoistinen** [comment]
No, no custom template. And yes, Google seem to be going out of their way to make it complicated =(.

**Comment by mkoistinen** [comment]
Has anyone had any success here?

**Comment by mishbahr** [comment]
Sorry .. I did not get a chance to further look into this.

**Comment by githingeorge** [comment]
The script element that loads the API is missing the required authentication parameter. If you are using the standard Maps JavaScript API, you must use a key parameter with a valid API key. If you are a Premium Plan customer, you must use either a client parameter with your client ID or a key parameter with a valid API key.

As per Google recent announcement, usage of the Google Maps APIs now requires a key. If you are using the Google Maps API on localhost or your domain was not active prior to June 22nd, 2016, it will require a key going forward. Please see the Google Maps APIs documentation to get a key and add it to your application.

**Comment by githingeorge** [comment]
The url generated is: 

```
<script type="text/javascript" src="//maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=true"></script>
```

but the url needed is like:

```
<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>
```

**Comment by mishbahr** [comment]
I added the API key to the url in this commit: https://github.com/mishbahr/djangocms-gmaps/commit/13a12ed9153a8def7cac8fe1fe790b5df22a9a05

But for @mkoistinen it only works on localhost .. not sure why.

**Comment by githingeorge** [comment]
if u pip install it doesn't pull the latest changes, and it will work in localhost for everyone..see my above comment

**Comment by mishbahr** [comment]
I haven't pushed the latest change to PyPi yet.

**Comment by mishbahr** [comment]
To use "async defer" I will need to change the javascript to load after callback.

**Comment by mishbahr** [comment]
Refactored some of the JavaScript .. seems to working fine locally. Can you guys try? 
@mkoistinen @githingeorge 
<img width="760" alt="" src="https://cloud.githubusercontent.com/assets/1264089/18414431/5a35a48e-77bf-11e6-9625-892cd8bbc338.png">

**Comment by githingeorge** [comment]
Yup i integrated latest commit, its working now...
http://maijomoto.com/en/find-us/locations/

**Comment by mishbahr** [comment]
Awesome. I'll push it to PyPi tonight. Thanks for you help.

**Comment by mishbahr** [comment]
Pushed to PyPi https://pypi.python.org/pypi/djangocms-gmaps/0.1.5.0

**Comment by mishbahr** [comment]
@mkoistinen Updated aldryn config file to include API key settings. Given that its a compulsory field .. will it cause any problems w/ existing  `djangocms-gmaps` installs in Aldryn?

**Comment by mkoistinen** [comment]
Sorry, this issue is not fixed =(. Even @githingeorge's site does not work:

![image](https://cloud.githubusercontent.com/assets/615759/19018165/86a660fa-8825-11e6-8820-7a091cf21f22.png)

(Note, there are no displayed maps on that site.)

I haven't looked too deeply into it, but it appears that the gmaps.js needs to be written to detect the async loading from the google api, then run, only once it is available.

I've tried changing Google's script-tag to not use async, but it doesn't seem to help. =(

**Comment by mishbahr** [comment]
Are you sure? Try doing a force refresh. I'm on mobile so can't upload a screenshot. It works fine for me. @githingeorge  can you confirm?

**Comment by githingeorge** [comment]
Its not working now.
gmaps.js script tag is loaded after loading google maps. Can you load gmaps.js first then google maps...

**Comment by mkoistinen** [comment]
@githingeorge I've tried that already but overriding the template in my project. It didn't seem to help =(
